// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqu_w2hahG8juzYjz3ifon46Qg4w4T8rw',
    appId: '1:1055732038819:web:e040c076e1ea63146ad316',
    messagingSenderId: '1055732038819',
    projectId: 'c2mlotty',
    authDomain: 'c2mlotty.firebaseapp.com',
    storageBucket: 'c2mlotty.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqu_w2hahG8juzYjz3ifon46Qg4w4T8rw',
    appId: '1:1055732038819:android:e040c076e1ea63146ad316',
    messagingSenderId: '1055732038819',
    projectId: 'c2mlotty',
    authDomain: 'c2mlotty.firebaseapp.com',
    storageBucket: 'c2mlotty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqu_w2hahG8juzYjz3ifon46Qg4w4T8rw',
    appId: '1:1055732038819:ios:e040c076e1ea63146ad316',
    messagingSenderId: '1055732038819',
    projectId: 'c2mlotty',
    authDomain: 'c2mlotty.firebaseapp.com',
    storageBucket: 'c2mlotty.firebasestorage.app',
    iosBundleId: 'com.c2m.lottyMemoryGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqu_w2hahG8juzYjz3ifon46Qg4w4T8rw',
    appId: '1:1055732038819:ios:e040c076e1ea63146ad316',
    messagingSenderId: '1055732038819',
    projectId: 'c2mlotty',
    authDomain: 'c2mlotty.firebaseapp.com',
    storageBucket: 'c2mlotty.firebasestorage.app',
    iosBundleId: 'com.c2m.lottyMemoryGame',
  );
}
